---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: events-workload
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-creator
rules:
- apiGroups: [""] 
  resources: ["pods", "deployments"]
  verbs: ["get", "watch", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-creator-binding
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-creator 
subjects: 
- kind: ServiceAccount
  name: events-workload